name: Docker Image

on:
  push:
    tags:
      - "v*"

env:
  DOCKER_REPO_N_GATEWAY: ghcr.io/nahidalibrary/galaxy/n-gateway
  DOCKER_REPO_N_SVC_ACCOUNT: ghcr.io/nahidalibrary/galaxy/n-svc-account
  DOCKER_REPO_N_SVC_CORE: ghcr.io/nahidalibrary/galaxy/n-svc-core

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -DskipTests=true package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push n-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./n-gateway
          file: ./n-gateway/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO_N_GATEWAY }}:latest
            ${{ env.DOCKER_REPO_N_GATEWAY }}:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push n-svc-core
        uses: docker/build-push-action@v5
        with:
          context: ./n-svc-core
          file: ./n-svc-core/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO_N_SVC_CORE }}:latest
            ${{ env.DOCKER_REPO_N_SVC_CORE }}:${{ steps.get_version.outputs.VERSION }}
  
#      - name: Webhook
#        run: |
#          curl --location --request GET '${{ secrets.WEBHOOK_URL }}'
